-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 07:51:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TEACHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TEACHER` (
  `PERSON_id` INT NOT NULL AUTO_INCREMENT,
  `SALARY` INT NOT NULL,
  `JOBTITLE` VARCHAR(45) NULL,
  `EmailAddress` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `ExperienceYears` VARCHAR(45) NULL,
  PRIMARY KEY (`PERSON_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSULTATION_HOURS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSULTATION_HOURS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
	`OpenTime` TIME NOT NULL,
	`CloseTime` TIME NULL,
  `Room` INT NOT NULL,
  `TEACHER_PERSON_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CONSULTATION_HOURS_TEACHER_idx` (`TEACHER_PERSON_id` ASC) VISIBLE,
  CONSTRAINT `fk_CONSULTATION_HOURS_TEACHER`
    FOREIGN KEY (`TEACHER_PERSON_id`)
    REFERENCES `mydb`.`TEACHER` (`PERSON_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
